default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

development:
  <<: *default
  database: aguiarassessoria_development
  username: dhiogoadmin
  password: dhiegodhiego

test:
  <<: *default
  database: aguiarassessoria_test
  username: dhiogoadmin
  password: dhiegodhiego

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "aguiarassessoria_production") %>
  username: <%= ENV.fetch("POSTGRES_USER", "dhiogoadmin") %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
